package ippprintclient

import (
	"bitbucket.org/papercutsoftware/gopapercut/print/ippclient/v3"
	"bitbucket.org/papercutsoftware/gopapercut/print/ippclient/v3/finishings"
)

var printerReadyAttributes = []string{
	ippclient.PrinterIsAcceptingJobs,
	ippclient.PrinterState,
	ippclient.PrinterStateReasons,
	ippclient.MediaColSupported,
	ippclient.PrinterMakeAndModel,
	ippclient.OperationsSupported,
	ippclient.IppVersionsSupported,
	ippclient.SidesSupported,
	ippclient.FinishingsSupported,
	ippclient.CopiesSupported,
	ippclient.DocumentFormatSupported,
	ippclient.DocumentFormatDefault,
	ippclient.PrinterDeviceId,
}

var finishingsStringToEnumMap = map[string]finishings.Finishings{
	// Generic
	"none":          finishings.FinishingsNone,
	"staple":        finishings.FinishingsStaple,
	"punch":         finishings.FinishingsPunch,
	"cover":         finishings.FinishingsCover,
	"bind":          finishings.FinishingsBind,
	"saddle-stitch": finishings.FinishingsSaddleStitch,
	"edge-stitch":   finishings.FinishingsSEdgeStitch,
	"fold":          finishings.FinishingsFold,
	"trim":          finishings.FinishingsTrim,
	"bale":          finishings.FinishingsBale,
	"booklet-maker": finishings.FinishingsBookletMaker,
	"job-offset":    finishings.FinishingsJogOffset,
	// Staple
	"staple-top-left":      finishings.FinishingsStapleTopLeft,
	"staple-bottom-left":   finishings.FinishingsStapleBottomLeft,
	"staple-top-right":     finishings.FinishingsStapleTopRight,
	"staple-bottom-right":  finishings.FinishingsStapleBottomRight,
	"staple-dual-left":     finishings.FinishingsStapleDualLeft,
	"staple-dual-top":      finishings.FinishingsStapleDualTop,
	"staple-dual-right":    finishings.FinishingsStapleDualRight,
	"staple-dual-bottom":   finishings.FinishingsStapleDualBottom,
	"staple-triple-left":   finishings.FinishingsStapleTripleLeft,
	"staple-triple-top":    finishings.FinishingsStapleTripleTop,
	"staple-triple-right":  finishings.FinishingsStapleTripleRight,
	"staple-triple-bottom": finishings.FinishingsStapleTripleBottom,
	// Stitch
	"edge-stitch-left":   finishings.FinishingsEdgeStitchLeft,
	"edge-stitch-top":    finishings.FinishingsEdgeStitchTop,
	"edge-stitch-right":  finishings.FinishingsEdgeStitchRight,
	"edge-stitch-bottom": finishings.FinishingsEdgeStitchBottom,
	// Bind
	"bind-left":   finishings.FinishingsBindLeft,
	"bind-top":    finishings.FinishingsBindTop,
	"bind-right":  finishings.FinishingsBindRight,
	"bind-bottom": finishings.FinishingsBindBottom,
	// Trim
	"trim-after-pages":     finishings.FinishingsTrimAfterPages,
	"trim-after-documents": finishings.FinishingsTrimAfterDocuments,
	"trim-after-copies":    finishings.FinishingsTrimAfterCopies,
	"trim-after-job":       finishings.FinishingsTrimAfterJob,
	// Punch
	"punch-top-left":      finishings.FinishingsPunchTopLeft,
	"punch-bottom-left":   finishings.FinishingsPunchBottomLeft,
	"punch-top-right":     finishings.FinishingsPunchTopRight,
	"punch-bottom-right":  finishings.FinishingsPunchBottomRight,
	"punch-dual-left":     finishings.FinishingsPunchDualLeft,
	"punch-dual-top":      finishings.FinishingsPunchDualTop,
	"punch-dual-right":    finishings.FinishingsPunchDualRight,
	"punch-dual-bottom":   finishings.FinishingsPunchDualBottom,
	"punch-triple-left":   finishings.FinishingsPunchTripleLeft,
	"punch-triple-top":    finishings.FinishingsPunchTripleTop,
	"punch-triple-right":  finishings.FinishingsPunchTripleRight,
	"punch-triple-bottom": finishings.FinishingsPunchTripleBottom,
	"punch-quad-left":     finishings.FinishingsPunchQuadLeft,
	"punch-quad-top":      finishings.FinishingsPunchQuadTop,
	"punch-quad-right":    finishings.FinishingsPunchQuadRight,
	"punch-quad-bottom":   finishings.FinishingsPunchQuadBottom,
	// Fold
	"fold-accordion":     finishings.FinishingsFoldAccordion,
	"fold-double-gate":   finishings.FinishingsFoldDoubleGate,
	"fold-gate":          finishings.FinishingsFoldGate,
	"fold-half":          finishings.FinishingsFoldHalf,
	"fold-half-z":        finishings.FinishingsFoldHalfZ,
	"fold-left-gate":     finishings.FinishingsFoldLeftGate,
	"fold-letter":        finishings.FinishingsFoldLetter,
	"fold-parallel":      finishings.FinishingsFoldParallel,
	"fold-poster":        finishings.FinishingsFoldPoster,
	"fold-right-gate":    finishings.FinishingsFoldRightGate,
	"fold-z":             finishings.FinishingsFoldZ,
	"fold-engineering-z": finishings.FinishingsFoldEngineeringZ,
}

var genericFinishings = map[finishings.Finishings]finishings.Finishings{
	// Staple
	finishings.FinishingsStapleTopLeft:      finishings.FinishingsStaple,
	finishings.FinishingsStapleBottomLeft:   finishings.FinishingsStaple,
	finishings.FinishingsStapleTopRight:     finishings.FinishingsStaple,
	finishings.FinishingsStapleBottomRight:  finishings.FinishingsStaple,
	finishings.FinishingsStapleDualLeft:     finishings.FinishingsStaple,
	finishings.FinishingsStapleDualTop:      finishings.FinishingsStaple,
	finishings.FinishingsStapleDualRight:    finishings.FinishingsStaple,
	finishings.FinishingsStapleDualBottom:   finishings.FinishingsStaple,
	finishings.FinishingsStapleTripleLeft:   finishings.FinishingsStaple,
	finishings.FinishingsStapleTripleTop:    finishings.FinishingsStaple,
	finishings.FinishingsStapleTripleRight:  finishings.FinishingsStaple,
	finishings.FinishingsStapleTripleBottom: finishings.FinishingsStaple,
	// Stitch
	finishings.FinishingsEdgeStitchLeft:   finishings.FinishingsSEdgeStitch,
	finishings.FinishingsEdgeStitchTop:    finishings.FinishingsSEdgeStitch,
	finishings.FinishingsEdgeStitchRight:  finishings.FinishingsSEdgeStitch,
	finishings.FinishingsEdgeStitchBottom: finishings.FinishingsSEdgeStitch,
	// Bind
	finishings.FinishingsBindLeft:   finishings.FinishingsBind,
	finishings.FinishingsBindTop:    finishings.FinishingsBind,
	finishings.FinishingsBindRight:  finishings.FinishingsBind,
	finishings.FinishingsBindBottom: finishings.FinishingsBind,
	// Trim
	finishings.FinishingsTrimAfterPages:     finishings.FinishingsTrim,
	finishings.FinishingsTrimAfterDocuments: finishings.FinishingsTrim,
	finishings.FinishingsTrimAfterCopies:    finishings.FinishingsTrim,
	finishings.FinishingsTrimAfterJob:       finishings.FinishingsTrim,
	// Punch
	finishings.FinishingsPunchTopLeft:      finishings.FinishingsPunch,
	finishings.FinishingsPunchBottomLeft:   finishings.FinishingsPunch,
	finishings.FinishingsPunchTopRight:     finishings.FinishingsPunch,
	finishings.FinishingsPunchBottomRight:  finishings.FinishingsPunch,
	finishings.FinishingsPunchDualLeft:     finishings.FinishingsPunch,
	finishings.FinishingsPunchDualTop:      finishings.FinishingsPunch,
	finishings.FinishingsPunchDualRight:    finishings.FinishingsPunch,
	finishings.FinishingsPunchDualBottom:   finishings.FinishingsPunch,
	finishings.FinishingsPunchTripleLeft:   finishings.FinishingsPunch,
	finishings.FinishingsPunchTripleTop:    finishings.FinishingsPunch,
	finishings.FinishingsPunchTripleRight:  finishings.FinishingsPunch,
	finishings.FinishingsPunchTripleBottom: finishings.FinishingsPunch,
	finishings.FinishingsPunchQuadLeft:     finishings.FinishingsPunch,
	finishings.FinishingsPunchQuadTop:      finishings.FinishingsPunch,
	finishings.FinishingsPunchQuadRight:    finishings.FinishingsPunch,
	finishings.FinishingsPunchQuadBottom:   finishings.FinishingsPunch,
	// Fold
	finishings.FinishingsFoldAccordion:    finishings.FinishingsFold,
	finishings.FinishingsFoldDoubleGate:   finishings.FinishingsFold,
	finishings.FinishingsFoldGate:         finishings.FinishingsFold,
	finishings.FinishingsFoldHalf:         finishings.FinishingsFold,
	finishings.FinishingsFoldHalfZ:        finishings.FinishingsFold,
	finishings.FinishingsFoldLeftGate:     finishings.FinishingsFold,
	finishings.FinishingsFoldLetter:       finishings.FinishingsFold,
	finishings.FinishingsFoldParallel:     finishings.FinishingsFold,
	finishings.FinishingsFoldPoster:       finishings.FinishingsFold,
	finishings.FinishingsFoldRightGate:    finishings.FinishingsFold,
	finishings.FinishingsFoldZ:            finishings.FinishingsFold,
	finishings.FinishingsFoldEngineeringZ: finishings.FinishingsFold,
}
